services:
  portal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - "./src:/app/src"
      - "./public:/app/public"
