const userSelectionsTypes = {
    FETCH_USERSELECTIONS_BEGIN: 'FETCH_USERSELECTIONS_BEGIN',
    FETCH_USERSELECTIONS_SUCCESS: 'FETCH_USERSELECTIONS_SUCCESS',
    FETCH_USERSELECTIONS_FAILURE: 'FETCH_USERSELECTIONS_FAILURE',
    UPDATE_USERSELECTIONS: 'UPDATE_USERSELECTIONS'
  };
  
export default userSelectionsTypes;