const userSelectionsTypes = {
    FETCH_USERSELECTIONS_BEGIN: 'FETCH_USERSELECTIONS_BEGIN',
    FETCH_USERSELECTIONS_SUCCESS: 'FETCH_USERSELECTIONS_SUCCESS',
    FETCH_USERSELECTIONS_FAILURE: 'FETCH_USERSELECTIONS_FAILURE'
  };
  
export default userSelectionsTypes;